# TCL File Generated by Component Editor 14.1
# Mon Feb 09 08:53:04 JST 2015
# DO NOT MODIFY


# 
# axi_i2c "axi_i2c" v1.0
#  2015.02.09.08:53:04
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module axi_i2c
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi_i2c
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axi_i2c
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL aq_axi_i2c
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aq_axi_i2c.v VERILOG PATH aq_axi_i2c.v TOP_LEVEL_FILE
add_fileset_file aq_axi_lite_slave.v VERILOG PATH aq_axi_lite_slave.v
add_fileset_file aq_i2c_master.v VERILOG PATH aq_i2c_master.v
add_fileset_file aq_i2c_slave_model.v VERILOG PATH aq_i2c_slave_model.v
add_fileset_file ram32x256.v VERILOG PATH ram32x256.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point I2C
# 
add_interface I2C conduit end
set_interface_property I2C associatedClock ""
set_interface_property I2C associatedReset ""
set_interface_property I2C ENABLED true
set_interface_property I2C EXPORT_OF ""
set_interface_property I2C PORT_NAME_MAP ""
set_interface_property I2C CMSIS_SVD_VARIABLES ""
set_interface_property I2C SVD_ADDRESS_GROUP ""

add_interface_port I2C I2C_SDA sda Bidir 1
add_interface_port I2C I2C_SCL scl Output 1


# 
# connection point RESET_N
# 
add_interface RESET_N reset end
set_interface_property RESET_N associatedClock ""
set_interface_property RESET_N synchronousEdges NONE
set_interface_property RESET_N ENABLED true
set_interface_property RESET_N EXPORT_OF ""
set_interface_property RESET_N PORT_NAME_MAP ""
set_interface_property RESET_N CMSIS_SVD_VARIABLES ""
set_interface_property RESET_N SVD_ADDRESS_GROUP ""

add_interface_port RESET_N ARESETN reset_n Input 1


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 0
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK S_AXI_ACLK clk Input 1


# 
# connection point AXI4_LS
# 
add_interface AXI4_LS axi4lite end
set_interface_property AXI4_LS associatedClock CLK
set_interface_property AXI4_LS associatedReset RESET_N
set_interface_property AXI4_LS readAcceptanceCapability 1
set_interface_property AXI4_LS writeAcceptanceCapability 1
set_interface_property AXI4_LS combinedAcceptanceCapability 1
set_interface_property AXI4_LS readDataReorderingDepth 1
set_interface_property AXI4_LS bridgesToMaster ""
set_interface_property AXI4_LS ENABLED true
set_interface_property AXI4_LS EXPORT_OF ""
set_interface_property AXI4_LS PORT_NAME_MAP ""
set_interface_property AXI4_LS CMSIS_SVD_VARIABLES ""
set_interface_property AXI4_LS SVD_ADDRESS_GROUP ""

add_interface_port AXI4_LS S_AXI_AWADDR awaddr Input 16
add_interface_port AXI4_LS S_AXI_AWPROT awprot Input 3
add_interface_port AXI4_LS S_AXI_AWVALID awvalid Input 1
add_interface_port AXI4_LS S_AXI_AWREADY awready Output 1
add_interface_port AXI4_LS S_AXI_WDATA wdata Input 32
add_interface_port AXI4_LS S_AXI_WSTRB wstrb Input 4
add_interface_port AXI4_LS S_AXI_WVALID wvalid Input 1
add_interface_port AXI4_LS S_AXI_WREADY wready Output 1
add_interface_port AXI4_LS S_AXI_BVALID bvalid Output 1
add_interface_port AXI4_LS S_AXI_BREADY bready Input 1
add_interface_port AXI4_LS S_AXI_BRESP bresp Output 2
add_interface_port AXI4_LS S_AXI_ARADDR araddr Input 16
add_interface_port AXI4_LS S_AXI_ARPROT arprot Input 3
add_interface_port AXI4_LS S_AXI_ARVALID arvalid Input 1
add_interface_port AXI4_LS S_AXI_ARREADY arready Output 1
add_interface_port AXI4_LS S_AXI_RDATA rdata Output 32
add_interface_port AXI4_LS S_AXI_RRESP rresp Output 2
add_interface_port AXI4_LS S_AXI_RVALID rvalid Output 1
add_interface_port AXI4_LS S_AXI_RREADY rready Input 1

